// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace HappyEarthConsignment.Models
{
    [Table("OrderLineItem")]
    public partial class OrderLineItem
    {
        [Key]
        [Column("OrderLineItemID")]
        public int OrderLineItemId { get; set; }
        [Column("OrderID")]
        public int OrderId { get; set; }
        [Column("ProductID")]
        public int ProductId { get; set; }

        [ForeignKey(nameof(OrderId))]
        [InverseProperty("OrderLineItems")]
        public virtual Order Order { get; set; }
        [ForeignKey(nameof(ProductId))]
        [InverseProperty("OrderLineItems")]
        public virtual Product Product { get; set; }
    }
}