// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace HappyEarthConsignment.Models
{
    [Table("Product")]
    public partial class Product
    {
        public Product()
        {
            OrderLineItems = new HashSet<OrderLineItem>();
        }

        [Key]
        [Column("ProductID")]
        public int ProductId { get; set; }
        [Column("CategoryID")]
        public int CategoryId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(255)]
        public string Description { get; set; }
        [Required]
        [StringLength(1)]
        public string Gender { get; set; }
        [Required]
        [StringLength(20)]
        public string Brand { get; set; }
        [Required]
        [StringLength(10)]
        public string Condition { get; set; }
        [Required]
        [StringLength(5)]
        public string Size { get; set; }
        [Column(TypeName = "money")]
        public decimal Price { get; set; }
        [Required]
        [StringLength(2)]
        public string Available { get; set; }
        [StringLength(255)]
        public string Photo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty(nameof(ProductCategory.Products))]
        public virtual ProductCategory Category { get; set; }
        [InverseProperty(nameof(OrderLineItem.Product))]
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }


    }
}